### ISSUE TITLE
I'm having trouble with Day 2

### ISSUE THREAD

**Issue by ZebGirouard** [den-wdi-2/schedule#1]
http://www.cricbuzz.com/cricket-news/83665/live-cricket-score-of-pakistan-vs-west-indies-3rd-test-day-2-at-sharjah

http://www.day2.co.uk/#firstpage

I talked to Nick, and he didn't know anything about Day 2 either.

The second lesson was Box Model and Positioning.  I am wondering why it can't be Sphere Model and Positioning.  Why only rectangles?

**Comment by gliechty** [comment]
I'm having trouble centering a 'button' over a 'banner'...it's not really a banner since I'm not assigning an absolute position. Tried block, inline block and inline with 0 auto and other xx auto margins, but haven't had any luck. I spoke with Brian, and we're both at a loss here. Stack overflow wasn't much help, those 'buttons' were functional and were positioned over different kinds of banners.
